
name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Enable Windows
        run: flutter config --enable-windows-desktop
      - name: Get packages
        run: flutter pub get
      - name: Build Windows
        run: flutter build windows --release
      - name: Zip EXE
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath deadlines_manager_windows.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deadlines_manager_windows
          path: deadlines_manager_windows.zip
